version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    # volumes:
    #   - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres_data:
